name: Start Dump

on: 
  workflow_dispatch:
    inputs:
      minecraftVersion:
        description: 'Minecraft Version'
        required: true
        default: '1.16'

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - name: Clone McDataExtracting
      run: git clone https://github.com/u9g/McDataExtracting code
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '15'
    - name: Setup Java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x ./code/gradlew
    - name: Generate Config
      run: cd code && npm run start -- ${{ github.event.inputs.minecraftVersion }}
    - name: Delete Node Modules
      run: rm -Rf code/node_modules
    - name: Run Gradle
      run: gradle run
    - name: Move json
      run: mkdir json && mv code/blockCollisionShapes.json json/blockCollisionShapes.json
    - name: Save to Artifact
      uses: actions/upload-artifact@v2
      with:
        name: data
        path: json
