name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        description: 'Version of minecraft to dump data from'
        default: '1.16.5'
        required: true

jobs:
    dump-shapes:
      runs-on: ubuntu-latest
      steps:
      - run: git clone https://github.com/PrismarineJS/McDataExtracting code
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Run npm
        run: npm run start -- ${{ github.event.inputs.minecraftVersion }}
      - name: rm node_modules
        run: rm -Rf node_modules
      - name: make dir for json
        run: mkdir json && mv blockCollisionShapes.json json/blockCollisionShapes.json
      - name: save to artifact
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: json
